import type { Brand, Category, Product, Review } from '@/types'

// Mirrors supabase/seed.sql — used only when Supabase is not configured (demo mode).
export const demoCategories: Category[] = [
  { id: 'c1', name: 'Smartphones', slug: 'smartphones', parent_id: null },
  { id: 'c2', name: 'Laptops', slug: 'laptops', parent_id: null },
  { id: 'c3', name: 'Audio', slug: 'audio', parent_id: null },
  { id: 'c4', name: 'Gaming', slug: 'gaming', parent_id: null },
  { id: 'c5', name: 'Displays & TV', slug: 'displays-tv', parent_id: null },
  { id: 'c6', name: 'Accessories', slug: 'accessories', parent_id: null },
  { id: 'c7', name: 'PC Gamer', slug: 'pc-gamer', parent_id: null },
  { id: 'c8', name: 'Composants', slug: 'composants', parent_id: null },
  { id: 'c9', name: 'Périphériques', slug: 'peripheriques', parent_id: null },
  { id: 'c10', name: 'Smart Home', slug: 'smart-home', parent_id: null },
  { id: 'c11', name: 'PC Portables Gamer', slug: 'pc-portables-gamer', parent_id: 'c7' },
  { id: 'c12', name: 'PC Bureaux Gamer', slug: 'pc-bureaux-gamer', parent_id: 'c7' },
  { id: 'c13', name: 'Consoles', slug: 'consoles', parent_id: 'c7' },
  { id: 'c14', name: 'Android Phones', slug: 'android-phones', parent_id: 'c1' },
  { id: 'c15', name: 'iPhones', slug: 'iphones', parent_id: 'c1' },
  { id: 'c16', name: 'Ultrabooks', slug: 'ultrabooks', parent_id: 'c2' },
  { id: 'c17', name: 'MacBooks', slug: 'macbooks', parent_id: 'c2' },
  { id: 'c18', name: 'Headphones', slug: 'headphones', parent_id: 'c3' },
  { id: 'c19', name: 'Speakers', slug: 'speakers', parent_id: 'c3' },
  { id: 'c20', name: 'Earbuds', slug: 'earbuds', parent_id: 'c3' },
  { id: 'c21', name: 'Consoles & Games', slug: 'consoles-games', parent_id: 'c4' },
  { id: 'c22', name: 'Gaming Chairs', slug: 'gaming-chairs', parent_id: 'c4' },
  { id: 'c23', name: 'Monitors', slug: 'monitors', parent_id: 'c5' },
  { id: 'c24', name: 'TVs', slug: 'tvs', parent_id: 'c5' },
  { id: 'c25', name: 'Chargers & Cables', slug: 'chargers-cables', parent_id: 'c6' },
  { id: 'c26', name: 'Bags & Cases', slug: 'bags-cases', parent_id: 'c6' },
  { id: 'c27', name: 'Cartes Graphiques', slug: 'cartes-graphiques', parent_id: 'c8' },
  { id: 'c28', name: 'Processeurs', slug: 'processeurs', parent_id: 'c8' },
  { id: 'c29', name: 'Cartes Mères', slug: 'cartes-meres', parent_id: 'c8' },
  { id: 'c30', name: 'Stockage & RAM', slug: 'stockage-ram', parent_id: 'c8' },
  { id: 'c31', name: 'Claviers', slug: 'claviers', parent_id: 'c9' },
  { id: 'c32', name: 'Souris', slug: 'souris', parent_id: 'c9' },
  { id: 'c33', name: 'Webcams & Streaming', slug: 'webcams-streaming', parent_id: 'c9' },
  { id: 'c34', name: 'Aspirateurs Robots', slug: 'aspirateurs-robots', parent_id: 'c10' },
  { id: 'c35', name: 'Caméras & Sonnettes', slug: 'cameras-sonnettes', parent_id: 'c10' },
  { id: 'c36', name: 'Éclairage Connecté', slug: 'eclairage-connecte', parent_id: 'c10' },
]

export const demoBrands: Brand[] = [
  { id: 'b1', name: 'Apple' },
  { id: 'b2', name: 'Samsung' },
  { id: 'b3', name: 'Sony' },
  { id: 'b4', name: 'Lenovo' },
  { id: 'b5', name: 'JBL' },
  { id: 'b6', name: 'Logitech' },
  { id: 'b7', name: 'HP' },
  { id: 'b8', name: 'Xiaomi' },
  // Phones
  { id: 'b9', name: 'Google' },
  { id: 'b10', name: 'Huawei' },
  { id: 'b11', name: 'OnePlus' },
  { id: 'b12', name: 'OPPO' },
  { id: 'b13', name: 'vivo' },
  { id: 'b14', name: 'Honor' },
  { id: 'b15', name: 'Nothing' },
  { id: 'b16', name: 'Motorola' },
  { id: 'b17', name: 'realme' },
  { id: 'b18', name: 'Nokia' },
  // Computers & components
  { id: 'b19', name: 'Dell' },
  { id: 'b20', name: 'ASUS' },
  { id: 'b21', name: 'Acer' },
  { id: 'b22', name: 'MSI' },
  { id: 'b23', name: 'Microsoft' },
  { id: 'b24', name: 'Razer' },
  { id: 'b25', name: 'Gigabyte' },
  { id: 'b26', name: 'Alienware' },
  { id: 'b27', name: 'Intel' },
  { id: 'b28', name: 'AMD' },
  { id: 'b29', name: 'NVIDIA' },
  { id: 'b30', name: 'Corsair' },
  { id: 'b31', name: 'Kingston' },
  { id: 'b32', name: 'Seagate' },
  { id: 'b33', name: 'Western Digital' },
  // Audio
  { id: 'b34', name: 'Bose' },
  { id: 'b35', name: 'Sennheiser' },
  { id: 'b36', name: 'Bang & Olufsen' },
  { id: 'b37', name: 'Marshall' },
  { id: 'b38', name: 'Audio-Technica' },
  { id: 'b39', name: 'Beats' },
  { id: 'b40', name: 'Anker' },
  { id: 'b41', name: 'Shure' },
  { id: 'b42', name: 'Harman Kardon' },
  // Gaming
  { id: 'b43', name: 'Nintendo' },
  { id: 'b44', name: 'Valve' },
  { id: 'b45', name: 'SteelSeries' },
  { id: 'b46', name: 'HyperX' },
  { id: 'b47', name: 'Turtle Beach' },
  { id: 'b48', name: 'Elgato' },
  // Displays & TV
  { id: 'b49', name: 'LG' },
  { id: 'b50', name: 'TCL' },
  { id: 'b51', name: 'Hisense' },
  { id: 'b52', name: 'Philips' },
  { id: 'b53', name: 'Panasonic' },
  { id: 'b54', name: 'BenQ' },
  // Cameras & drones
  { id: 'b55', name: 'Canon' },
  { id: 'b56', name: 'Nikon' },
  { id: 'b57', name: 'Fujifilm' },
  { id: 'b58', name: 'GoPro' },
  { id: 'b59', name: 'DJI' },
  { id: 'b60', name: 'Insta360' },
  // Smart home & accessories
  { id: 'b61', name: 'Dyson' },
  { id: 'b62', name: 'Ring' },
  { id: 'b63', name: 'TP-Link' },
  { id: 'b64', name: 'Garmin' },
  { id: 'b65', name: 'Fitbit' },
  { id: 'b66', name: 'Belkin' },
  { id: 'b67', name: 'Satechi' },
  { id: 'b68', name: 'Kindle' },
]

export const demoProducts: Product[] = [
  {
    id: 'p1', name: 'iPhone 16 Pro',
    description: 'Flagship smartphone with a titanium frame, A18 Pro chip and a 48 MP triple-camera system. Stunning 6.3" LTPO OLED display with 120 Hz ProMotion.',
    price: 13999, stock: 14, category_id: 'c15', brand_id: 'b1',
    images: ['products/iphone-16-pro.jpg'],
    specs: { Display: '6.3" LTPO OLED, 120 Hz', Chip: 'A18 Pro', Storage: '256 GB', Camera: '48 MP triple system', Battery: 'Up to 27 h video', Connectivity: '5G, Wi-Fi 7, USB-C' },
    is_featured: true, created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'p2', name: 'Samsung Galaxy S25 Ultra',
    description: 'Pro-grade Android flagship with embedded S Pen, 200 MP camera and Galaxy AI. 6.9" QHD+ Dynamic AMOLED 2X display.',
    price: 12499, stock: 9, category_id: 'c14', brand_id: 'b2',
    images: ['products/galaxy-s25-ultra.jpg'],
    specs: { Display: '6.9" QHD+ AMOLED 2X, 120 Hz', Chip: 'Snapdragon 8 Elite', Storage: '512 GB', Camera: '200 MP quad system', Battery: '5 000 mAh, 45 W', 'S Pen': 'Included' },
    is_featured: false, created_at: '2026-08-02T10:00:00Z',
  },
  {
    id: 'p3', name: 'MacBook Air 15" M4',
    description: 'Impossibly thin laptop with the M4 chip, 18-hour battery life and a brilliant 15.3" Liquid Retina display. Silent, fanless design.',
    price: 15999, stock: 7, category_id: 'c17', brand_id: 'b1',
    images: ['products/macbook-air-15.jpg'],
    specs: { Display: '15.3" Liquid Retina', Chip: 'Apple M4, 10-core', RAM: '16 GB unified', Storage: '512 GB SSD', Battery: 'Up to 18 h', Weight: '1.51 kg' },
    is_featured: true, created_at: '2026-08-03T10:00:00Z',
  },
  {
    id: 'p4', name: 'Lenovo Legion 5 Pro',
    description: 'Serious gaming power: RTX 4070 graphics, Ryzen 9 CPU and a 16" WQXGA 240 Hz display in a cool, quiet chassis.',
    price: 14499, stock: 5, category_id: 'c11', brand_id: 'b4',
    images: ['products/legion-5-pro.jpg'],
    specs: { Display: '16" WQXGA IPS, 240 Hz', CPU: 'Ryzen 9 7945HX', GPU: 'RTX 4070 8 GB', RAM: '32 GB DDR5', Storage: '1 TB SSD', Keyboard: 'RGB backlit' },
    is_featured: false, created_at: '2026-08-04T10:00:00Z',
  },
  {
    id: 'p5', name: 'Sony WH-1000XM5',
    description: 'Industry-leading noise cancelling wireless headphones with 30-hour battery, crystal-clear calls and hi-res audio.',
    price: 3899, stock: 21, category_id: 'c18', brand_id: 'b3',
    images: ['products/sony-xm5.jpg'],
    specs: { Type: 'Over-ear, wireless', ANC: 'Adaptive noise cancelling', Battery: '30 h (ANC on)', Drivers: '30 mm', Codecs: 'LDAC, AAC, SBC', Weight: '250 g' },
    is_featured: true, created_at: '2026-08-05T10:00:00Z',
  },
  {
    id: 'p6', name: 'JBL Flip 6',
    description: 'Portable Bluetooth speaker with bold JBL Original Pro sound, IP67 waterproofing and 12 hours of playtime.',
    price: 1199, stock: 30, category_id: 'c19', brand_id: 'b5',
    images: ['products/jbl-flip-6.jpg'],
    specs: { Type: 'Portable Bluetooth', Battery: '12 h', Rating: 'IP67 dust/waterproof', Power: '30 W RMS', Pairing: 'PartyBoost', Weight: '550 g' },
    is_featured: false, created_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'p7', name: 'Logitech MX Master 3S',
    description: 'Iconic wireless productivity mouse: 8K DPI sensor, MagSpeed scroll wheel and quiet clicks. Pairs with 3 devices.',
    price: 999, stock: 25, category_id: 'c32', brand_id: 'b6',
    images: ['products/mx-master-3s.jpg'],
    specs: { Sensor: '8 000 DPI Darkfield', Scroll: 'MagSpeed electromagnetic', Battery: '70 days, USB-C', Devices: '3, Easy-Switch', Connectivity: 'Bluetooth / Bolt' },
    is_featured: false, created_at: '2026-08-07T10:00:00Z',
  },
  {
    id: 'p8', name: 'HP OMEN 27" QHD 165 Hz',
    description: '27" QHD gaming monitor with 165 Hz refresh, 1 ms response and HDR. Sharp, fluid and color-accurate.',
    price: 3499, stock: 11, category_id: 'c23', brand_id: 'b7',
    images: ['products/omen-27.jpg'],
    specs: { Size: '27"', Resolution: '2560 x 1440 QHD', Refresh: '165 Hz, 1 ms GtG', Panel: 'IPS, HDR 400', Ports: '2x HDMI, 1x DP', Sync: 'Adaptive-Sync' },
    is_featured: false, created_at: '2026-08-08T10:00:00Z',
  },
  {
    id: 'p9', name: 'Xiaomi Robot Vacuum X10',
    description: 'Smart robot vacuum with 4000 Pa suction, LiDAR navigation and app control. Vacuums and mops in one pass.',
    price: 2999, stock: 8, category_id: 'c34', brand_id: 'b8',
    images: ['products/xiaomi-x10.jpg'],
    specs: { Suction: '4 000 Pa', Navigation: 'LiDAR + vSLAM', Battery: '5 200 mAh, 180 min', Modes: 'Vacuum + mop', Control: 'App, Alexa, Google', Dustbin: '400 ml' },
    is_featured: false, created_at: '2026-08-09T10:00:00Z',
  },
  {
    id: 'p10', name: 'PlayStation 5 Slim',
    description: 'Next-gen console in a slimmer design: lightning-fast 1 TB SSD, ray tracing and 4K gaming up to 120 fps.',
    price: 5499, stock: 6, category_id: 'c13', brand_id: 'b3',
    images: ['products/ps5-slim.jpg'],
    specs: { Storage: '1 TB SSD', Output: '4K up to 120 fps, 8K ready', Audio: 'Tempest 3D', Controller: 'DualSense haptics', Drive: 'Ultra HD Blu-ray', Model: 'Slim' },
    is_featured: true, created_at: '2026-08-10T10:00:00Z',
  },
]

export const demoReviews: Review[] = [
  { id: 'r1', product_id: 'p1', user_id: 'demo', rating: 5, comment: 'Camera is unreal and the battery easily lasts a full day.', created_at: '2026-08-20T12:00:00Z', author: 'Yassine' },
  { id: 'r2', product_id: 'p1', user_id: 'demo2', rating: 4, comment: 'Fast and gorgeous. A bit pricey, but worth it.', created_at: '2026-08-22T12:00:00Z', author: 'Salma' },
  { id: 'r3', product_id: 'p5', user_id: 'demo', rating: 5, comment: 'Noise cancelling is incredible on the bus to work.', created_at: '2026-08-19T12:00:00Z', author: 'Omar' },
  { id: 'r4', product_id: 'p3', user_id: 'demo3', rating: 5, comment: 'Silent, fast, and the screen is beautiful. Perfect laptop.', created_at: '2026-08-25T12:00:00Z', author: 'Kenza' },
  { id: 'r5', product_id: 'p10', user_id: 'demo2', rating: 5, comment: 'Loads games instantly. The DualSense haptics are next level.', created_at: '2026-08-21T12:00:00Z', author: 'Mehdi' },
  { id: 'r6', product_id: 'p8', user_id: 'demo', rating: 4, comment: 'Great colors and super smooth at 165 Hz.', created_at: '2026-08-23T12:00:00Z', author: 'Nadia' },
]

export const demoAdmin = {
  id: 'demo-admin-id',
  email: 'admin@electrogega.ma',
  display_name: 'Demo Admin',
  phone: '+212600000000',
  role: 'admin' as const,
  created_at: '2026-08-01T09:00:00Z',
}

export const demoCustomer = {
  id: 'demo-customer-id',
  email: 'customer@electrogega.ma',
  display_name: 'Demo Customer',
  phone: null,
  role: 'customer' as const,
  created_at: '2026-08-02T09:00:00Z',
}
